// <auto-generated />
namespace PdomingosTodos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versao20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao20));
        
        string IMigrationMetadata.Id
        {
            get { return "202106010603123_versao20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
