// <auto-generated />
namespace PdomingosTodos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versao18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao18));
        
        string IMigrationMetadata.Id
        {
            get { return "202106010459028_versao18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
